sudo: required
services:
        - docker
before-install:
        - docker build -t nv185001/docker-react -f DockerFile .

script: 
        - docker run nv185001/docker-react npm run test -- --coverage
